---
title: "Total_Deaths"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(flexdashboard)
```

Total Deaths
```{r, echo=FALSE}
data <- read.csv('Weekly_counts_of_death_by_jurisdiction_and_cause_of_death.csv')

data <- data.frame(Jurisdiction = data$Jurisdiction, Year = data$Year, Cause = data$Cause.Group, Deaths = data$Number.of.Deaths)

data <- na.omit(data)

totalDeaths.all <- sum(data$Deaths)

deaths_2015.df <- filter(data, data$Year == "2015")
deaths_2016.df <- filter(data, data$Year == "2016")
deaths_2017.df <- filter(data, data$Year == "2017")
deaths_2018.df <- filter(data, data$Year == "2018")
deaths_2019.df <- filter(data, data$Year == "2019")
deaths_2020.df <- filter(data, data$Year == "2020")

deaths.collection <- c(sum(deaths_2015.df$Deaths), sum(deaths_2016.df$Deaths), sum(deaths_2017.df$Deaths), sum(deaths_2018.df$Deaths), sum(deaths_2019.df$Deaths), sum(deaths_2020.df$Deaths))

df.totalDeaths <- data.frame(Year = c(2015, 2016, 2017, 2018, 2019, 2020), Deaths = c(deaths.collection[1], deaths.collection[2], deaths.collection[3], deaths.collection[4], deaths.collection[5], deaths.collection[6]), Death.Percentage = c(deaths.collection[1]/sum(deaths.collection), deaths.collection[2]/sum(deaths.collection), deaths.collection[3]/sum(deaths.collection), deaths.collection[4]/sum(deaths.collection), deaths.collection[5]/sum(deaths.collection), deaths.collection[6]/sum(deaths.collection)))

names(df.totalDeaths) <- c("Year", "Deaths", "Death Rate")

chart1 <- ggplot(data = df.totalDeaths, aes(x = Year, y = Deaths)) +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 1)) +
  labs(title = "DEATHS PER YEAR", subtitle = "Updated Dec. 9, 2020") +
  geom_col(fill = df.totalDeaths$Deaths) +
  geom_text(aes(label = Deaths))

plot(x = df.totalDeaths$Year, y = df.totalDeaths$Deaths, pch = 21, col = "blue", bg = "red3", main = "Distance from the Mean", xlab = "Year", ylab = "Deaths")
abline(h = mean(deaths.collection), col = 'green')

m <- c()

for (i in 1:6) {
  lines(c(df.totalDeaths$Year[i], df.totalDeaths$Year[i]), c(mean(df.totalDeaths$Deaths), df.totalDeaths$Deaths[i]), col = 'red')
  m <- c(m, df.totalDeaths$Deaths[i] - mean(df.totalDeaths$Deaths)) 
}

m.df <- data.frame(Year = c(2015, 2016, 2017, 2018, 2019, 2020), Mean = mean(df.totalDeaths$Deaths), Deaths.Mean = m)

names(m.df) = c("Year", "Mean", "Deaths Above or Below the Mean")

m.df

plt <-ggplot(data = df.totalDeaths, aes(x = Year, y = Deaths)) +
  geom_point(aes(col = Deaths), alpha = 1, shape = 4, stroke = 2) +
  xlab("Year") +
  ylab("Deaths") +
  ggtitle(label = "DEATHS PER YEAR", subtitle = "Updated Dec 9, 2020") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 1)) +
  geom_line(aes(Year, Deaths))
plt
```


```{r, echo=FALSE}
alzheimer.df <- filter(data, Cause == "Alzheimer disease and dementia")
circulatoryDiseases.df <- filter(data, Cause == "Circulatory diseases")
malignantNeoplasms.df <- filter(data, Cause == "Malignant neoplasms")
otherSelectCauses.df <- filter(data, Cause == "Other select causes")
respiratoryDiseases.df <- filter(data, Cause == "Respiratory diseases")

deaths.alzheimer <- sum(alzheimer.df$Deaths)
deaths.circulatoryDiseases <- sum(circulatoryDiseases.df$Deaths)
deaths.malignantNeoplasms <- sum(malignantNeoplasms.df$Deaths)
deaths.otherSelectCauses <- sum(otherSelectCauses.df$Deaths)
deaths.respiratoryDiseases <- sum(respiratoryDiseases.df$Deaths)

alz.perc <- deaths.alzheimer/sum(deaths.collection)
circ.perc <- deaths.circulatoryDiseases/sum(deaths.collection)
mal.perc <- deaths.malignantNeoplasms/sum(deaths.collection)
oth.perc <- deaths.otherSelectCauses/sum(deaths.collection)
resp.perc <- deaths.respiratoryDiseases/sum(deaths.collection)

deaths.causes.df <- data.frame(Cause = c("Circulatory diseases", "Malignant neoplasms", "Respiratory diseases", "Alzheimer disease and dementia", "Other select causes"), Deaths = c(deaths.circulatoryDiseases, deaths.malignantNeoplasms, deaths.respiratoryDiseases, deaths.alzheimer, deaths.otherSelectCauses), Death.Rate = c(circ.perc, mal.perc, resp.perc, alz.perc, oth.perc))

deaths.causes.df$Rank <- seq(1,5)

rank <- seq(1,5)
dc.mat <- rbind(c(deaths.causes.df[,2], deaths.causes.df[,3], rank))
dc.mat <- matrix(dc.mat, ncol = 3)

dimnames(dc.mat)[[1]] <- c("Circulatory", "Malignant", "Respiratory", "Alzheimer", "Other")
dimnames(dc.mat)[[2]] <- c("Deaths", "Death Rate", "Rank")
```


Deaths by Cause and Year
```{r echo=FALSE}
alzheimer.2015.df <- filter(data, Cause == "Alzheimer disease and dementia" & Year == 2015)
alzheimer.2016.df <- filter(data, Cause == "Alzheimer disease and dementia" & Year == 2016)
alzheimer.2017.df <- filter(data, Cause == "Alzheimer disease and dementia" & Year == 2017)
alzheimer.2018.df <- filter(data, Cause == "Alzheimer disease and dementia" & Year == 2018)
alzheimer.2019.df <- filter(data, Cause == "Alzheimer disease and dementia" & Year == 2019)
alzheimer.2020.df <- filter(data, Cause == "Alzheimer disease and dementia" & Year == 2020)

circulatory.2015.df <- filter(data, Cause == "Circulatory diseases" & Year == 2015)
circulatory.2016.df <- filter(data, Cause == "Circulatory diseases" & Year == 2016)
circulatory.2017.df <- filter(data, Cause == "Circulatory diseases" & Year == 2017)
circulatory.2018.df <- filter(data, Cause == "Circulatory diseases" & Year == 2018)
circulatory.2019.df <- filter(data, Cause == "Circulatory diseases" & Year == 2019)
circulatory.2020.df <- filter(data, Cause == "Circulatory diseases" & Year == 2020)

malignant.2015.df <- filter(data, Cause == "Malignant neoplasms" & Year == 2015)
malignant.2016.df <- filter(data, Cause == "Malignant neoplasms" & Year == 2016)
malignant.2017.df <- filter(data, Cause == "Malignant neoplasms" & Year == 2017)
malignant.2018.df <- filter(data, Cause == "Malignant neoplasms" & Year == 2018)
malignant.2019.df <- filter(data, Cause == "Malignant neoplasms" & Year == 2019)
malignant.2020.df <- filter(data, Cause == "Malignant neoplasms" & Year == 2020)

other.2015.df <- filter(data, Cause == "Other select causes" & Year == 2015)
other.2016.df <- filter(data, Cause == "Other select causes" & Year == 2016)
other.2017.df <- filter(data, Cause == "Other select causes" & Year == 2017)
other.2018.df <- filter(data, Cause == "Other select causes" & Year == 2018)
other.2019.df <- filter(data, Cause == "Other select causes" & Year == 2019)
other.2020.df <- filter(data, Cause == "Other select causes" & Year == 2020)

respiratory.2015.df <- filter(data, Cause == "Respiratory diseases" & Year == 2015)
respiratory.2016.df <- filter(data, Cause == "Respiratory diseases" & Year == 2016)
respiratory.2017.df <- filter(data, Cause == "Respiratory diseases" & Year == 2017)
respiratory.2018.df <- filter(data, Cause == "Respiratory diseases" & Year == 2018)
respiratory.2019.df <- filter(data, Cause == "Respiratory diseases" & Year == 2019)
respiratory.2020.df <- filter(data, Cause == "Respiratory diseases" & Year == 2020)

alz.deaths <- c(sum(alzheimer.2015.df$Deaths), sum(alzheimer.2016.df$Deaths), sum(alzheimer.2017.df$Deaths), sum(alzheimer.2018.df$Deaths), sum(alzheimer.2019.df$Deaths), sum(alzheimer.2020.df$Deaths))

circ.deaths <- c(sum(circulatory.2015.df$Deaths), sum(circulatory.2016.df$Deaths), sum(circulatory.2017.df$Deaths), sum(circulatory.2018.df$Deaths), sum(circulatory.2019.df$Deaths), sum(circulatory.2020.df$Deaths))

malignant.deaths <- c(sum(malignant.2015.df$Deaths), sum(malignant.2016.df$Deaths), sum(malignant.2017.df$Deaths), sum(malignant.2018.df$Deaths), sum(malignant.2019.df$Deaths), sum(malignant.2020.df$Deaths))

other.deaths <- c(sum(other.2015.df$Deaths), sum(other.2016.df$Deaths), sum(other.2017.df$Deaths), sum(other.2018.df$Deaths), sum(other.2019.df$Deaths), sum(other.2020.df$Deaths))

respiratory.deaths <- c(sum(respiratory.2015.df$Deaths), sum(respiratory.2016.df$Deaths), sum(respiratory.2017.df$Deaths), sum(respiratory.2018.df$Deaths), sum(respiratory.2019.df$Deaths), sum(respiratory.2020.df$Deaths))

years <- c(2015, 2016, 2017, 2018, 2019, 2020)

catDeaths.df <- data.frame(as.factor(years), alz.deaths, circ.deaths, malignant.deaths, other.deaths, respiratory.deaths)

names(catDeaths.df) <- c("Year", "Alzheimer disease and dementia", "Circulatory diseases", "Malignant neoplasms", "Other select causes", "Respiratory diseases")

# Number of deaths per category per year
r <- rbind(c(catDeaths.df$`Alzheimer disease and dementia`, catDeaths.df$`Circulatory diseases`, catDeaths.df$`Malignant neoplasms`, catDeaths.df$`Other select causes`, catDeaths.df$`Respiratory diseases`))
mat <- matrix(r, ncol = 5)

dimnames(mat)[[1]] <- c(2015, 2016, 2017, 2018, 2019, 2020)
dimnames(mat)[[2]] <- c("Alzheimer", "Circulatory", "Malignant", "Other", "Respiratory")

# Percentage of deaths per category per year
percent.2015 <- c(catDeaths.df[1,2]/sum(catDeaths.df[1,2:6]), catDeaths.df[1,3]/sum(catDeaths.df[1,2:6]), catDeaths.df[1,4]/sum(catDeaths.df[1,2:6]), catDeaths.df[1,5]/sum(catDeaths.df[1,2:6]), catDeaths.df[1,6]/sum(catDeaths.df[1,2:6]))

percent.2016 <- c(catDeaths.df[2,2]/sum(catDeaths.df[2,2:6]), catDeaths.df[2,3]/sum(catDeaths.df[2,2:6]), catDeaths.df[2,4]/sum(catDeaths.df[2,2:6]), catDeaths.df[2,5]/sum(catDeaths.df[2,2:6]), catDeaths.df[2,6]/sum(catDeaths.df[2,2:6]))

percent.2017 <- c(catDeaths.df[3,2]/sum(catDeaths.df[3,2:6]), catDeaths.df[3,3]/sum(catDeaths.df[3,2:6]), catDeaths.df[3,4]/sum(catDeaths.df[3,2:6]), catDeaths.df[3,5]/sum(catDeaths.df[3,2:6]), catDeaths.df[3,6]/sum(catDeaths.df[3,2:6]))

percent.2018 <- c(catDeaths.df[4,2]/sum(catDeaths.df[4,2:6]), catDeaths.df[4,3]/sum(catDeaths.df[4,2:6]), catDeaths.df[4,4]/sum(catDeaths.df[4,2:6]), catDeaths.df[4,5]/sum(catDeaths.df[4,2:6]), catDeaths.df[4,6]/sum(catDeaths.df[4,2:6]))

percent.2019 <- c(catDeaths.df[5,2]/sum(catDeaths.df[5,2:6]), catDeaths.df[5,3]/sum(catDeaths.df[5,2:6]), catDeaths.df[5,4]/sum(catDeaths.df[5,2:6]), catDeaths.df[5,5]/sum(catDeaths.df[5,2:6]), catDeaths.df[5,6]/sum(catDeaths.df[5,2:6]))

percent.2020 <- c(catDeaths.df[6,2]/sum(catDeaths.df[6,2:6]), catDeaths.df[6,3]/sum(catDeaths.df[6,2:6]), catDeaths.df[6,4]/sum(catDeaths.df[6,2:6]), catDeaths.df[6,5]/sum(catDeaths.df[6,2:6]), catDeaths.df[6,6]/sum(catDeaths.df[6,2:6]))

m.mat <- rbind(percent.2015, percent.2016, percent.2017, percent.2018, percent.2019, percent.2020)
dimnames(m.mat)[[1]] <- c(2015, 2016, 2017, 2018, 2019, 2020)
dimnames(m.mat)[[2]] <- c("Alzheimer", "Circulatory", "Malignant", "Other", "Respiratory")

mm.df <- data.frame(m.mat[,1], m.mat[,2], m.mat[,3], m.mat[,4], m.mat[,5])
names(mm.df) <- c("Alzheimer", "Circulatory", "Malignant", "Other", "Respiratory")

# Highest number of deaths in each category per year. 1 = highest and 5 = lowest
place.2015 <- c(4, 1, 2, 5, 3)
place.2016 <- c(4, 1, 2, 5, 3)
place.2017 <- c(4, 1, 2, 5, 3)
place.2018 <- c(4, 1, 2, 5, 3)
place.2019 <- c(3, 1, 2, 5, 4)
place.2020 <- c(3, 1, 2, 5, 4)

mt <- rbind(place.2015, place.2016, place.2017, place.2018, place.2019, place.2020)
dimnames(mt)[[1]] <- c(2015, 2016, 2017, 2018, 2019, 2020)
dimnames(mt)[[2]] <- c("Alzheimer", "Circulatory", "Malignant", "Other", "Respiratory")

mat
mt
```


```{r, echo=FALSE}
# Total Deaths
chart1
df.totalDeaths

# Deaths by Cause
mat # Deaths per category per year
deaths.causes.df # Total deaths per category
dc.mat
mm.df # Percentage per category per year
mt # Rank per category per year
```

